---
title: '14'
author: "Rachael Hall"
date: "2/20/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
counts <- read.csv("data/airway_scaledcounts.csv", stringsAsFactors = FALSE)
metadata <-  read.csv("data/airway_metadata.csv", stringsAsFactors = FALSE)
```

```{r}
head(counts)
head(metadata)
```
```{r}
View(metadata)
```

```{r}
## how many genes are u dealing with? 
nrow(counts)
```
```{r}
metadata$dex == "control"

```

```{r}
## avg counts per gene for control samples and for drug treated samples. then compare values to see overall difference 
## access only control rows in metadata 
##use $id of control data to access control columns in counts and calculate the avg 
control <- metadata[metadata$dex == "control",]
control
control.mean <- rowSums(counts[ ,control$id] )/4 
control.mean
names(control.mean) <- counts$ensgene

```
```{r}
treated <- metadata[metadata$dex == "treated",]
treated.mean <- rowSums(counts[ ,treated$id] )/nrow(treated) 
treated.mean
```
```{r}
meancounts <- data.frame(control.mean, treated.mean)
meancounts
```

```{r}
## make a log log plot 
plot.default(meancounts, log = 'xy')
```

```{r}
meancounts$log2fc <- log2(meancounts[,"treated.mean"]/meancounts[,"control.mean"])
head(meancounts)
```
```{r}
## remove any gene that has zero avg counts 
zero.vals <- which(meancounts[,1:2]==0, arr.ind=TRUE)

to.rm <- unique(zero.vals[,1])
mycounts <- meancounts[-to.rm,]
head(mycounts)
```

```{r}
## how many genes left?
nrow(mycounts)
```

```{r}
up.ind <- mycounts$log2fc > 2
down.ind <- mycounts$log2fc < (-2)
```
```{r}
sum(up.ind)
sum(down.ind)
```
```{r}
library(DESeq2)

```

```{r}
#3 setup input for DESeq by specifying countdata, metadata and the design 

dds <- DESeqDataSetFromMatrix(countData=counts, 
                              colData=metadata, 
                              design=~dex, 
                              tidy=TRUE)
dds
```


```{r}
dds <- DESeq(dds)
```

```{r}
results(dds)
```
```{r}
res <- results(dds)
```

```{r}
res$sig <- res$padj<0.05 & abs(res$log2FoldChange)>2
mycols <- rep("grey", nrow(res))
plot( res$log2FoldChange,  -log(res$padj), col = mycols)

```


```{r}
mycols <- rep("gray", nrow(res))
mycols[ abs(res$log2FoldChange) > 2 ]  <- "pink" 
mycols[ abs(res$log2FoldChange) < -2 ]  <- "pink" 
plot( res$log2FoldChange,  -log(res$padj), col = mycols)
abline(v=c(-2,2), col="gray", lty=2)
abline(h=-log(0.05))
```




